import type { Metadata } from "next";
import "./globals.css";
import { Ubuntu } from "next/font/google";
import NavBar from "@/Components/NavBar/NavBar";
const ubuntu = Ubuntu({
  weight: ["400", "500","700"], 
  subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Parella",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={ubuntu.className}
      >
        <main className="w-full">
          <NavBar />
          {children}
          </main>
        
      </body>
    </html>
  );
}
