import type { Metadata } from "next";
import "./globals.css";
import { Ubuntu } from "next/font/google";
import Footer from '../Components/footer/Footer'
import NavBarContainer from "@/Components/NavBar/NavBarContainer";
const ubuntu = Ubuntu({
  weight: ["400", "500", "700"],
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Parella",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={ubuntu.className}
      >
        <main className="w-full">
          <NavBarContainer />
          {children}
          <Footer />
        </main>

      </body>
    </html>
  );
}
